//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int idCita { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> estado { get; set; }
        public string estadoCita { get; set; }
        public int idPaciente { get; set; }
        public int idHorarioMedico { get; set; }
        public Nullable<System.TimeSpan> horaCita { get; set; }
    
        public virtual HorarioMedicos HorarioMedicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
