//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadMedicos
    {
        public int idMedicoEspecialidad { get; set; }
        public int idEspecialidad { get; set; }
        public int idMedico { get; set; }
    
        public virtual Especialidades Especialidades { get; set; }
        public virtual Medicos Medicos { get; set; }
    }
}
