//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioMedicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorarioMedicos()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public int idHorarioMedico { get; set; }
        public int idHorario { get; set; }
        public int idMedico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Horarios Horarios { get; set; }
        public virtual Medicos Medicos { get; set; }
    }
}
